on: [push]

name: Dead Code Analysis

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - name: Nix dead code analysis
        run: 'nix run nixpkgs#deadnix -- --fail .'
        shell: bash
        id: deadnix